use crate::skill::Skill;

pub struct Skills {
    academics: Skill,
    athletics: Skill,
    battle: Skill,
    boating: Skill,
    common_knowledge: Skill,
    driving: Skill,
    electronics: Skill,
    faith: Skill,
    fighting: Skill,
    focus: Skill,
    gambling: Skill,
    hacking: Skill,
    healing: Skill,
    intimidation: Skill,
    language: Skill,
    notice: Skill,
    occult: Skill,
    performance: Skill,
    persuasion: Skill,
    piloting: Skill,
    psionics: Skill,
    repair: Skill,
    research: Skill,
    riding: Skill,
    science: Skill,
    shooting: Skill,
    spellcasting: Skill,
    stealth: Skill,
    survival: Skill,
    taunt: Skill,
    thievery: Skill,
    weird_science: Skill,
}
