[package]
name = "savage-worlds-rs"
version = "0.1.0"
authors = ["Jason Becker"]
edition = "2018"
license-file = "LICENSE-FAN"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
regex = "1"
rocket = "0.4.5"
